blank_issues_enabled: true
contact_links:
  - name: ğŸ› Bug Reports
    url: https://github.com/NightMira/amxModX_MultiMod-MirGame/issues/new?template=bug_report.md
    about: Report a bug or compilation issue
  - name: âœ¨ Feature Request
    url: https://github.com/NightMira/amxModX_MultiMod-MirGame/issues/new?template=bug_report.md
    about: Feature Request